HTML Reporter - headers fixed, tests scrollable
qunitjs/qunit pull request #1513
Opened 2020-11-18 19:05 UTC by BryanCrotaz

CSS change to keep test headers fixed at the top and make test results scrollable. Much improved dev experience.

Fixes #1512

2020-11-19 07:14 UTC, bertdeblock commented
Nice! This has been bugging me as well. Though it seems that QUnit follows jQuery's browser support policy, which still includes IE9+ among others. I'm not 100% sure, but I'm guessing CSS features like `calc`, `vw`, `vh` and `flex` related styles might cause issues for older browsers?

2020-11-19 09:18 UTC, BryanCrotaz commented
How many developers use quint in IE9? I could understand if it was going out to the public but this is for devs.

2020-11-19 10:57 UTC, bertdeblock commented
Maybe there are still teams out there that run their tests in older browsers as part of their CI/CD flow? It seems there have been CSS adjustments in the past to fix issues, so it doesn't seem that far-fetched to me that adding new styles should take into account the browser support policy. I could be wrong of course and if so, I apologise in advance. I'm sure someone of the QUnit team can confirm. Thanks for the fix anyways, will really improve the DX 👍.

2020-11-19 12:08 UTC, BryanCrotaz commented
removed flexbox, vh and calc. Not responsive to header height any more. Suggest that flexbox is reinstated once the requirement to support IE9 is removed.

2020-11-19 14:28 UTC, BryanCrotaz commented
I have signed the licence but it says I haven't...

2020-11-19 14:30 UTC, BryanCrotaz commented
> run their tests in older browsers as part of their CI/CD flow

Ah yes of course

2020-11-19 16:47 UTC, smcclure15 commented
I can't stress enough how UX-friendly of a fix this is - I can certainly commiserate. Thanks for contributing!

The hardcoded pixel values are going to be hard to remain robust and flexible. I gave it bash with different window widths, and some get pretty due to the different line-wrapping:

![image](https://user-images.githubusercontent.com/20109108/99696411-a9db2000-2a5c-11eb-9fa8-7237155d1bcc.png)

![image](https://user-images.githubusercontent.com/20109108/99696530-cb3c0c00-2a5c-11eb-9d36-28017fc03a25.png)

![image](https://user-images.githubusercontent.com/20109108/99696569-d55e0a80-2a5c-11eb-8148-588700505ce8.png)

![image](https://user-images.githubusercontent.com/20109108/99696617-e149cc80-2a5c-11eb-8d88-809146e29e82.png)

2020-11-19 17:00 UTC, BryanCrotaz commented
> The hardcoded pixel values are going to be hard to remain robust and flexible

Absolutely - that's why I'd like to use flexbox. Frankly if someone is using this in CI in IE9 they don't care about the UX, only the results. Can we use flexbox and have a fallback to the old behaviour?

2020-11-20 02:10 UTC, Krinkle requested changes
I like this a lot!

Would it be possible to achieve this in a way that we only add styles to our own `qunit-` elements? In particular, styling the `body` element tends to cause test failures for integration tests that may temporarily render a UI component in a fixture or at the end of the body.

2020-11-20 03:39 UTC, BryanCrotaz commented
> Would it be possible to achieve this

Yes. See new commit.

2020-11-20 03:43 UTC, BryanCrotaz commented
> The hardcoded pixel values are going to be hard to remain robust and flexible

I think that the best solution is flexbox - it will fall back to the current layout in IE9 - that's not broken, it's just not better.

2020-11-22 13:05 UTC, BryanCrotaz commented
Here's the final version - does nothing if flexbox isn't supported, so has no effect on old browsers.

2020-11-22 22:53 UTC, Krinkle commented
Noticed two issues when trying this out in the qunitjs.com demo.

| Before | After
|--|-
| ![a](https://user-images.githubusercontent.com/156867/99919434-5515fe80-2d15-11eb-9fb8-0d212c3c55ca.png) | ![b](https://user-images.githubusercontent.com/156867/99919431-547d6800-2d15-11eb-91ba-d34e0ae28da8.png)

1. The pass/fail banner gets reduced to 1px due to it having no content and thus the default flex shrinking behaviour reduces its height. Technically scrollable, but not useful.
2. At short viewports, the scrollable area can be below the fold and thus unreachable (<360px), but even if it's somewhere between 360 and 500, it is still relatively difficult to read and scroll.

Perhaps we could wrap these rules in a media query for `min-height: 500px`. The banner issue could be addressed by something like `#qunit-banner { flex: 5px 0 0; }`

2020-11-23 09:30 UTC, BryanCrotaz commented
@krinkle good spot, fixed

2020-11-23 10:50 UTC, BryanCrotaz commented
Test failure seems unrelated to the changes

2020-11-29 19:44 UTC, Krinkle commented
- Used tabs for consistency with the rest of the file.
- Restored relation betwen "Font Family and Sizes" comment and its related code.

2020-11-29 19:44 UTC, Krinkle approved these changes

2020-11-29 19:51 UTC, Krinkle commented
@BryanCrotaz This is good to go, but for the CLA signature pending.

2020-11-29 22:35 UTC, BryanCrotaz commented
> @BryanCrotaz This is good to go, but for the CLA signature pending.

I've signed it but it still says it's pending. When I click on the pending notice it takes me to the form and says I've already signed it. Where do I go from here?

2020-11-30 00:29 UTC, Krinkle commented
Looks good now. Not sure what it was... Thank you!

2020-11-30 00:33 UTC, merged