Core: refactor diff to do less slow mutations
qunitjs/qunit pull request #1697
Opened 2022-07-05 23:45 UTC by izelnakri

2022-07-06 01:27 UTC, Krinkle requested changes

2022-07-08 00:09 UTC, izelnakri commented on src/core/utilities.js
> +    if (!b.includes(item)) {
:+1:  done

2022-07-08 01:10 UTC, Krinkle commented
Confirmed results via a quick run on <https://www.measurethat.net/Benchmarks/Show/19727/0/filter-vs-reduce-vs-slice-splice>. Several orders of magnitudes indeed. I also ran a third variant there with `.filter()`.

I'm ready to land this, and will do so tomorrow either way as it's a clear improvement. I'm curious though if you avoided `.filter()` intentionally?

2022-07-08 16:38 UTC, izelnakri commented
> I'm ready to land this, and will do so tomorrow either way as it's a clear improvement. I'm curious though if you avoided `.filter()` intentionally?

I haven't thought of this, indeed it could be `.filter()` :sweat_smile: I created another commit for filter change, feel free to merge/delete them as you see fit!

2022-07-09 00:04 UTC, Krinkle approved these changes

2022-07-09 00:07 UTC, merged