Core: Fix compatibility with sinon.useFakeTimers in IE
qunitjs/qunit pull request #1738
Opened 2024-02-07 15:38 UTC by timmywil

The Promise polyfill needed to save the unmodified setImmediate function in IE to use for Promise._immediateFn

2024-02-07 21:06 UTC, Krinkle commented on test/main/promise.js
> +      globalNS.setImmediate = this.setImmediate;
This leaves behind an undefined global property in environments where the property did not exist. Can we avoid that?

2024-02-07 21:08 UTC, Krinkle commented on lib/promise-polyfill.js
> +// @ts-ignore
Please update the `Patches for use in QUnit:` header to document this local patch, to make sure we remember it in the future :)

2024-02-07 21:09 UTC, Krinkle requested changes
Two inline issues commented.

2024-02-08 13:02 UTC, Krinkle approved these changes

2024-02-08 13:16 UTC, Krinkle commented
Looks like GitHub got itself in some kind of broken state, not agreeing on which commit's status to look at for the merge button, thus blocking me from merging due to waiting for a status that would never come. Closing and re-opening fixed this.

2024-02-08 13:21 UTC, merged

2024-02-08 15:00 UTC, timmywil commented
Thanks! If you could do a release, I can update the jQuery branch.

2024-04-15 17:58 UTC, Dearley78 reviewed
lib/promise-polyfill.js